### ISSUE TITLE
tcpdial: remote host as telnet port/protocol makes simh segfault

### ISSUE THREAD

**Issue by b4** [DoctorWkt/4bsd-uucp#9]
I have NO IDEA what is happening...but trying to uucico to DECVAX (can't get tcpser to work) using tcpdial results in simh segfaulting...presumably because data is being input/output too fast?

**Comment by b4** [comment]
debugging on says:

#0  $a.51 () at sim_tmxr.c:1967
        tmp = 24 '\030'
        i = 0
        nbytes = 3
        j = 0
        lp = (TMLN *) 0x215ea000
#1  0x000e3e30 in $a.51 () at sim_tmxr.c:1851
        tmp = 24 '\030'
        i = 0
        nbytes = 3
        j = 0
        lp = (TMLN *) 0x215ea000

1967 is:                         (tmp == TN_KERMIT)) { ... gonna be protocol definitions of somesort
1851 is:                     tmxr_rmvrc (lp, j);                 /* remove char */

My guess...no handling for telnet so it explodes?

        {TN_KERMIT, "TN_KERMIT"},             /* KERMIT */

**Comment by dugoh** [comment]
See [here](https://github.com/DoctorWkt/4bsd-uucp#disabling-the-telnet-protocol)
decvax already has 1 line configured with notelnet on 5001
I guess this probably works a lot better if outbound and inbound have this turned off. Now it is like having Annex boxen mangling traffic in between.

**Comment by b4** [comment]
Can you set this on the connect port?

**Comment by dugoh** [comment]
Yes, see [sim_tmxr.c](https://raw.githubusercontent.com/simh/simh/c94659571f3061f6869e31e9f63cb7da8a404854/sim_tmxr.c)
```
    Direct computer to computer connections (Virutal Null Modem cables) may 
    be established using the telnet protocol or via raw tcp sockets.
     
        sim> attach MUX Line=2,Connect=host:port{;notelnet}
```

**Comment by b4** [comment]
That seems to have fixed the segfaulting...but as the remote end is ACTUALLY A TELNET SERVER, things were unhappy ;)

**Comment by dugoh** [comment]
Yeah, decvax has both now.
mcvax$ nc simh.tuhs.org **5000**|od -c|head -1
0000000 377 373   " 377 373 003 377 373 001 377 373  \0 377 375  \0  \n

mcvax$ nc simh.tuhs.org **5001**|od -c|head -1
0000000  \r  \n  \r  \n   4   .   3       B   S   D       U   N   I   X
